### ISSUE TITLE
Data link not working

### ISSUE THREAD

**Issue by alexhernandezgarcia** [6759-Project/cnn-downscaling#6]
Hey, did you (re)move the data on the linked [Google Drive](https://drive.google.com/drive/folders/1_ML9zY6t6W4jSg7jzN8SpERxfkVZBSBJ?usp=sharing)?

**Comment by JakeColor** [comment]
Hey @alexhernandezgarcia  sorry i missed this... yes I did; it was taking up quite a bit of space on my personal Drive. sorry about that!
